// Landing page data schema
// This contract is shared between Flask backend and Next.js frontend

export interface LandingPageData {
  id: string;

  // Course information
  course: {
    title: string;
    description: string;
    extendedDescription?: string;
    schedule: {
      dates?: string;
      time?: string;
      days?: string;
    };
    location?: string;
    duration?: string;
    targetAudience?: string;
  };

  // Visual assets (generated by Gemini)
  assets: {
    backgroundUrl?: string; // data:image/png;base64,... or URL
    bannerUrl?: string;
  };

  // Theme/colors (extracted from banner)
  theme?: {
    primary?: string; // e.g., "#13ecda"
    accent?: string;
    fontFamily?: string; // e.g., "Heebo"
  };

  // Registration form configuration
  form: {
    requiresInterview: boolean;
    referralOptions: string[];
  };

  // Metadata
  createdAt?: string;
}

// API response wrapper
export interface LandingApiResponse {
  success: boolean;
  data?: LandingPageData;
  error?: string;
}
